repos:
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: v1.6.0
    hooks:
      - id: baseline
        pass_filenames: false
      - id: commit
        pass_filenames: true

  - repo: local
    hooks:
      - id: lint
        name: Lint check
        entry: npm run validate:all
        language: system
        pass_filenames: false

      - id: spellcheck
        name: Spell check
        entry: npm run spellcheck
        language: system
        pass_filenames: false
