---
# Per environment values which override defaults in hmpps-template-typescript/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    hosts:
      - reuse-library-preprod.apps.live.cloud-platform.service.justice.gov.uk
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: reuse-library-preprod-gov-reuse-green
      external-dns.alpha.kubernetes.io/aws-weight: "100"

  env:
    INGRESS_URL: "https://reuse-library-preprod.apps.live.cloud-platform.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://reuse-library-preprod.apps.live.cloud-platform.service.justice.gov.uk'
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"
    SEARCH_API_URL: "http://localhost:8080"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
