---
# Per environment values which override defaults in hmpps-template-typescript/values.yaml

generic-service:
  replicaCount: 2

  podDisruptionBudget:
    enabled: false

  ingress:
    hosts:
      - reuse-library-dev.apps.live.cloud-platform.service.justice.gov.uk
      - dev.reuselibrary.service.justice.gov.uk
    tlsSecretName: reuse-library-cert
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: reuse-library-dev-gov-reuse-green
      external-dns.alpha.kubernetes.io/aws-weight: "100"
      external-dns.alpha.kubernetes.io/exclude: "dev.reuselibrary.service.justice.gov.uk"
#      nginx.ingress.kubernetes.io/server-alias: dev.reuselibrary.service.justice.gov.uk

  env:
    INGRESS_URL: "https://dev.reuselibrary.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://dev.reuselibrary.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    SEARCH_API_URL: "http://localhost:8080"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
